# Generated by Django 5.0.4 on 2024-05-07 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievedThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.FileField(default='/media/achieved.png/', null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('achieved_date', models.DateField()),
                ('text', models.CharField(max_length=2000)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'achievedthings',
            },
        ),
        migrations.CreateModel(
            name='ToDoThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.FileField(default='/media/todo.png/', null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('target_date', models.DateField()),
                ('reason', models.CharField(max_length=2000)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todothings',
            },
        ),
        migrations.CreateModel(
            name='WantItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('detail', models.CharField(max_length=1000)),
                ('picture', models.FileField(default='/media/item.png/', null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('target_date', models.DateField()),
                ('reason', models.CharField(max_length=2000)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wantitems',
            },
        ),
    ]
