# Generated by Django 5.0.4 on 2024-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievedthings',
            name='detail',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='todothings',
            name='detail',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='achievedthings',
            name='picture',
            field=models.FileField(default='/achieved.png/', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='todothings',
            name='picture',
            field=models.FileField(default='/todo.png/', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wantitems',
            name='picture',
            field=models.FileField(default='/item.png/', null=True, upload_to=''),
        ),
    ]
