# Generated by Django 5.0.4 on 2024-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_achievedthings_detail_todothings_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievedthings',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='todothings',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
