# Generated by Django 5.0.4 on 2024-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_achievedthings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievedthings',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
